{% set name = "ipyradiant" %}
{% set version = "0.1.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d7e2cfe36e8c5ab56bc99acd3453c39a17d993ce9cf408f95995b3534e0c03e5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - bokeh
    - datashader
    - holoviews
    - ipycytoscape >=1.0.3
    - ipywidgets
    - networkx >=2
    - pandas
    - python >=3.6
    - rdflib
    - rdflib-jsonld
    - scikit-image

test:
  imports:
    - ipyradiant
  commands:
    - python -m pip check
  requires:
    - pip

about:
  home: https://github.com/jupyrdf/ipyradiant
  summary: Jupyter Widgets for working with RDF graphs
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
    - zwelz3
