{% set version = "0.2.0" %}

package:
  name: ipyradiant
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/ipyradiant/ipyradiant-{{ version }}.tar.gz
  sha256: a81c9e12589a4fd9f6f680a8e068ac2693fdebb77394d4323685d9ae7c45be84

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - bokeh
    - datashader
    - holoviews
    - ipycytoscape >=1.2
    - ipywidgets >=7.6,<8
    - networkx >=2
    - pandas
    - python >={{ python_min }}
    - rdflib <7
    - rdflib-jsonld
    - scikit-image

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - ipyradiant
  commands:
    - pip check

about:
  home: https://github.com/jupyrdf/ipyradiant
  summary: Jupyter Widgets for working with RDF graphs
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
    - zwelz3
