{% set name = "ipyradiant" %}
{% set version = "0.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipyradiant-{{ version }}.tar.gz
  sha256: cc5b0057c88ec5f7d6f036effde9a5556d376f44fe95c141725e5df5093a6b0b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - bokeh
    - datashader
    - holoviews
    - ipycytoscape >=1.0.3
    - ipywidgets
    - networkx >=2
    - pandas
    - python >=3.6
    - qgrid
    - rdflib
    - rdflib-jsonld
    - scikit-image

test:
  imports:
    - ipyradiant
  commands:
    - python -m pip check
  requires:
    - pip

about:
  home: https://github.com/jupyrdf/ipyradiant
  summary: Jupyter Widgets for working with RDF graphs
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
