{% set name = "ipyradiant" %}
{% set version = "0.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a81c9e12589a4fd9f6f680a8e068ac2693fdebb77394d4323685d9ae7c45be84

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - bokeh
    - datashader
    - holoviews
    - ipycytoscape >=1.2
    - ipywidgets >=7.6,<8
    - networkx >=2
    - pandas
    - python >=3.6
    - rdflib
    - rdflib-jsonld
    - scikit-image

test:
  imports:
    - ipyradiant
  commands:
    - python -m pip check
  requires:
    - pip

about:
  home: https://github.com/jupyrdf/ipyradiant
  summary: Jupyter Widgets for working with RDF graphs
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
    - zwelz3
